<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class BooksTableSeeder extends Seeder
{
    public function run()
    {
        DB::table('books')->truncate();

        $books = [
            [
                'title' => 'The Fellowship of the Ring',
                'author' => 'J.R.R. Tolkien',
                'isbn' => '9780261102354',
                'genre' => 'Fantasy',
                'publication_year' => 1954,
                'publisher' => 'Allen & Unwin',
                'pages' => 423,
                'language' => 'English',
                'summary' => 'The first part of The Lord of the Rings trilogy, chronicling the journey of Frodo Baggins as he carries the One Ring toward Mount Doom.',
                'rating_avg' => 4.8,
                'number_of_reviews' => 8700,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => '1984',
                'author' => 'George Orwell',
                'isbn' => '9780451524935',
                'genre' => 'Science Fiction',
                'publication_year' => 1949,
                'publisher' => 'Secker & Warburg',
                'pages' => 328,
                'language' => 'English',
                'summary' => 'A dystopian novel set in a totalitarian society ruled by Big Brother and the Party, exploring themes of surveillance and truth.',
                'rating_avg' => 4.6,
                'number_of_reviews' => 12000,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'Pride and Prejudice',
                'author' => 'Jane Austen',
                'isbn' => '9780141439518',
                'genre' => 'Romance',
                'publication_year' => 1813,
                'publisher' => 'T. Egerton',
                'pages' => 279,
                'language' => 'English',
                'summary' => 'A classic novel that explores the emotional development of Elizabeth Bennet as she deals with issues of manners and marriage.',
                'rating_avg' => 4.5,
                'number_of_reviews' => 9900,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'The Da Vinci Code',
                'author' => 'Dan Brown',
                'isbn' => '9780307474278',
                'genre' => 'Thriller',
                'publication_year' => 2003,
                'publisher' => 'Doubleday',
                'pages' => 489,
                'language' => 'English',
                'summary' => 'A symbologist and cryptologist race through Europe uncovering clues hidden in famous artworks and churches.',
                'rating_avg' => 4.2,
                'number_of_reviews' => 13000,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'To Kill a Mockingbird',
                'author' => 'Harper Lee',
                'isbn' => '9780060935467',
                'genre' => 'Historical Fiction',
                'publication_year' => 1960,
                'publisher' => 'J.B. Lippincott & Co.',
                'pages' => 281,
                'language' => 'English',
                'summary' => 'A young girl reflects on the racial injustices and moral growth she witnesses in her Southern hometown.',
                'rating_avg' => 4.9,
                'number_of_reviews' => 9500,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'The Fault in Our Stars',
                'author' => 'John Green',
                'isbn' => '9780142424179',
                'genre' => 'Young Adult',
                'publication_year' => 2012,
                'publisher' => 'Dutton Books',
                'pages' => 313,
                'language' => 'English',
                'summary' => 'Two teenagers with cancer meet and fall in love while attending a support group, exploring themes of mortality and meaning.',
                'rating_avg' => 4.4,
                'number_of_reviews' => 7800,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'Becoming',
                'author' => 'Michelle Obama',
                'isbn' => '9781524763138',
                'genre' => 'Biography',
                'publication_year' => 2018,
                'publisher' => 'Crown Publishing Group',
                'pages' => 448,
                'language' => 'English',
                'summary' => 'Michelle Obama recounts her life, from her childhood in Chicago to becoming the First Lady of the United States.',
                'rating_avg' => 4.7,
                'number_of_reviews' => 10400,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'The Subtle Art of Not Giving a F*ck',
                'author' => 'Mark Manson',
                'isbn' => '9780062457714',
                'genre' => 'Self-Help',
                'publication_year' => 2016,
                'publisher' => 'Harper',
                'pages' => 224,
                'language' => 'English',
                'summary' => 'A counterintuitive approach to living a good life, rejecting positivity overload in favor of values and resilience.',
                'rating_avg' => 4.1,
                'number_of_reviews' => 9000,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'Harry Potter and the Sorcerer\'s Stone',
                'author' => 'J.K. Rowling',
                'isbn' => '9780439554930',
                'genre' => 'Fantasy',
                'publication_year' => 1997,
                'publisher' => 'Scholastic Corporation',
                'pages' => 309,
                'language' => 'English',
                'summary' => 'A young boy discovers he is a wizard and attends a magical school, where he makes friends and enemies.',
                'rating_avg' => 4.8,
                'number_of_reviews' => 15000,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'The Shining',
                'author' => 'Stephen King',
                'isbn' => '9780307743657',
                'genre' => 'Horror',
                'publication_year' => 1977,
                'publisher' => 'Doubleday',
                'pages' => 447,
                'language' => 'English',
                'summary' => 'A family becomes isolated in a haunted hotel during winter, leading the father to descend into madness.',
                'rating_avg' => 4.5,
                'number_of_reviews' => 8200,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'The Catcher in the Rye',
                'author' => 'J.D. Salinger',
                'isbn' => '9780316769488',
                'genre' => 'Young Adult',
                'publication_year' => 1951,
                'publisher' => 'Little, Brown and Company',
                'pages' => 277,
                'language' => 'English',
                'summary' => 'A teenage boy wanders through New York City, hating phonies and contemplating the ducks in Central Park. Deep stuff.',
                'rating_avg' => 4.0,
                'number_of_reviews' => 8100,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'Sapiens: A Brief History of Humankind',
                'author' => 'Yuval Noah Harari',
                'isbn' => '9780062316097',
                'genre' => 'Non-Fiction',
                'publication_year' => 2011,
                'publisher' => 'Harper',
                'pages' => 443,
                'language' => 'English',
                'summary' => 'An ambitious trek through the entirety of human history, from foraging to Facebook. Heavy, but worth the reps.',
                'rating_avg' => 4.6,
                'number_of_reviews' => 6700,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'The Alchemist',
                'author' => 'Paulo Coelho',
                'isbn' => '9780061122415',
                'genre' => 'Fiction',
                'publication_year' => 1988,
                'publisher' => 'HarperOne',
                'pages' => 208,
                'language' => 'English',
                'summary' => 'A shepherd boy follows a dream (literally) across the desert. Moral: your treasure might be under your nose. Or in Spain.',
                'rating_avg' => 4.4,
                'number_of_reviews' => 9200,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'Brave New World',
                'author' => 'Aldous Huxley',
                'isbn' => '9780060850524',
                'genre' => 'Science Fiction',
                'publication_year' => 1932,
                'publisher' => 'Chatto & Windus',
                'pages' => 268,
                'language' => 'English',
                'summary' => 'A future where happiness is chemically guaranteed and no one reads Shakespeare. Dystopia with a dose of soma.',
                'rating_avg' => 4.3,
                'number_of_reviews' => 7400,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'Educated',
                'author' => 'Tara Westover',
                'isbn' => '9780399590504',
                'genre' => 'Memoir',
                'publication_year' => 2018,
                'publisher' => 'Random House',
                'pages' => 334,
                'language' => 'English',
                'summary' => 'From an isolated, survivalist upbringing to earning a PhD from Cambridge — and no, it’s not fiction.',
                'rating_avg' => 4.7,
                'number_of_reviews' => 8500,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'The Little Prince',
                'author' => 'Antoine de Saint-Exupéry',
                'isbn' => '9780156012195',
                'genre' => 'Children\'s',
                'publication_year' => 1943,
                'publisher' => 'Reynal & Hitchcock',
                'pages' => 96,
                'language' => 'French',
                'summary' => 'A philosophical fox, a rose, and a boy from an asteroid. Children’s book? Maybe. Existential crisis? Definitely.',
                'rating_avg' => 4.9,
                'number_of_reviews' => 9300,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'The Road',
                'author' => 'Cormac McCarthy',
                'isbn' => '9780307387899',
                'genre' => 'Post-Apocalyptic',
                'publication_year' => 2006,
                'publisher' => 'Knopf',
                'pages' => 287,
                'language' => 'English',
                'summary' => 'A father and son wander through a scorched America, carrying hope, canned goods, and exactly one comma.',
                'rating_avg' => 4.2,
                'number_of_reviews' => 6900,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'A Game of Thrones',
                'author' => 'George R.R. Martin',
                'isbn' => '9780553593716',
                'genre' => 'Fantasy',
                'publication_year' => 1996,
                'publisher' => 'Bantam Books',
                'pages' => 835,
                'language' => 'English',
                'summary' => 'Winter is coming, and so are dragons, direwolves, and political betrayal at every feast.',
                'rating_avg' => 4.6,
                'number_of_reviews' => 11300,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'The Power of Habit',
                'author' => 'Charles Duhigg',
                'isbn' => '9780812981605',
                'genre' => 'Self-Help',
                'publication_year' => 2012,
                'publisher' => 'Random House',
                'pages' => 371,
                'language' => 'English',
                'summary' => 'Ever wondered why you always check your phone before bed? This book knows — and might help you stop.',
                'rating_avg' => 4.3,
                'number_of_reviews' => 8800,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'Dune',
                'author' => 'Frank Herbert',
                'isbn' => '9780441013593',
                'genre' => 'Science Fiction',
                'publication_year' => 1965,
                'publisher' => 'Chilton Books',
                'pages' => 412,
                'language' => 'English',
                'summary' => 'Spice, sandworms, space politics — and one young man with the destiny of a planet on his shoulders.',
                'rating_avg' => 4.7,
                'number_of_reviews' => 9500,
                'created_at' => now(),
                'updated_at' => now(),
            ],

        ];

        DB::table('books')->insert($books);
    }
}
