<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class FruitsTableSeeder extends Seeder
{
    public function run()
    {
        DB::table('fruits')->truncate();

        $fruits = [
            [
                'name' => 'Apple',
                'scientific_name' => 'Malus domestica',
                'color' => 'Red',
                'taste_profile' => 'Sweet',
                'season' => 'Autumn',
                'is_seasonal' => true,
                'price_per_kg' => 3.50,
                'origin_country' => 'USA',
                'description' => 'Crisp and juicy, apples are a popular fruit known for their balance of sweetness and tartness.',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Banana',
                'scientific_name' => 'Musa acuminata',
                'color' => 'Yellow',
                'taste_profile' => 'Sweet',
                'season' => 'All Year',
                'is_seasonal' => false,
                'price_per_kg' => 1.80,
                'origin_country' => 'Philippines',
                'description' => 'Bananas are soft, sweet fruits that are rich in potassium and perfect as a snack or smoothie base.',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Orange',
                'scientific_name' => 'Citrus sinensis',
                'color' => 'Orange',
                'taste_profile' => 'Tangy',
                'season' => 'Winter',
                'is_seasonal' => true,
                'price_per_kg' => 2.90,
                'origin_country' => 'Brazil',
                'description' => 'Oranges are juicy citrus fruits known for their refreshing flavor and high vitamin C content.',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Grape',
                'scientific_name' => 'Vitis vinifera',
                'color' => 'Purple',
                'taste_profile' => 'Juicy',
                'season' => 'Summer',
                'is_seasonal' => true,
                'price_per_kg' => 4.10,
                'origin_country' => 'Italy',
                'description' => 'Grapes come in many varieties and are commonly enjoyed fresh, dried, or made into wine.',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Mango',
                'scientific_name' => 'Mangifera indica',
                'color' => 'Yellow',
                'taste_profile' => 'Sweet',
                'season' => 'Summer',
                'is_seasonal' => true,
                'price_per_kg' => 2.75,
                'origin_country' => 'India',
                'description' => 'Mangoes are tropical fruits known for their juicy, aromatic sweetness and fibrous texture.',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Strawberry',
                'scientific_name' => 'Fragaria × ananassa',
                'color' => 'Red',
                'taste_profile' => 'Tangy',
                'season' => 'Spring',
                'is_seasonal' => true,
                'price_per_kg' => 4.25,
                'origin_country' => 'Spain',
                'description' => 'Strawberries are bright red, juicy fruits popular in desserts and smoothies.',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Pineapple',
                'scientific_name' => 'Ananas comosus',
                'color' => 'Brown',
                'taste_profile' => 'Tart',
                'season' => 'All Year',
                'is_seasonal' => false,
                'price_per_kg' => 3.10,
                'origin_country' => 'Thailand',
                'description' => 'Pineapples are tropical fruits with a tough outer shell and sweet, tart golden flesh.',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Watermelon',
                'scientific_name' => 'Citrullus lanatus',
                'color' => 'Green',
                'taste_profile' => 'Juicy',
                'season' => 'Summer',
                'is_seasonal' => true,
                'price_per_kg' => 1.60,
                'origin_country' => 'China',
                'description' => 'Watermelons are large, juicy fruits with a refreshing red interior perfect for hot days.',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Kiwi',
                'scientific_name' => 'Actinidia deliciosa',
                'color' => 'Brown',
                'taste_profile' => 'Tangy',
                'season' => 'Winter',
                'is_seasonal' => true,
                'price_per_kg' => 5.00,
                'origin_country' => 'New Zealand',
                'description' => 'Kiwis are small fruits with fuzzy skin and a bright green, tangy interior full of vitamin C.',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Avocado',
                'scientific_name' => 'Persea americana',
                'color' => 'Green',
                'taste_profile' => 'Creamy',
                'season' => 'Spring',
                'is_seasonal' => true,
                'price_per_kg' => 6.00,
                'origin_country' => 'Mexico',
                'description' => 'Avocados are creamy, nutrient-rich fruits widely used in salads, guacamole, and toasts.',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Blueberry',
                'scientific_name' => 'Vaccinium corymbosum',
                'color' => 'Blue',
                'taste_profile' => 'Mild',
                'season' => 'Summer',
                'is_seasonal' => true,
                'price_per_kg' => 7.50,
                'origin_country' => 'Canada',
                'description' => 'Blueberries are tiny, sweet berries rich in antioxidants and used in baking and smoothies.',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Lemon',
                'scientific_name' => 'Citrus limon',
                'color' => 'Yellow',
                'taste_profile' => 'Sour',
                'season' => 'Winter',
                'is_seasonal' => true,
                'price_per_kg' => 2.00,
                'origin_country' => 'Italy',
                'description' => 'Lemons are sour citrus fruits used for their juice, zest, and as a natural preservative.',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Peach',
                'scientific_name' => 'Prunus persica',
                'color' => 'Pink',
                'taste_profile' => 'Sweet',
                'season' => 'Summer',
                'is_seasonal' => true,
                'price_per_kg' => 4.00,
                'origin_country' => 'China',
                'description' => 'Peaches are juicy stone fruits with fuzzy skin and fragrant, sweet flesh.',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Pear',
                'scientific_name' => 'Pyrus communis',
                'color' => 'Green',
                'taste_profile' => 'Mild',
                'season' => 'Autumn',
                'is_seasonal' => true,
                'price_per_kg' => 3.60,
                'origin_country' => 'France',
                'description' => 'Pears are soft, grainy-textured fruits often enjoyed fresh or poached.',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Plum',
                'scientific_name' => 'Prunus domestica',
                'color' => 'Purple',
                'taste_profile' => 'Tart',
                'season' => 'Summer',
                'is_seasonal' => true,
                'price_per_kg' => 3.90,
                'origin_country' => 'Japan',
                'description' => 'Plums are juicy stone fruits with sweet to tart flavors, often used in jams and desserts.',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Coconut',
                'scientific_name' => 'Cocos nucifera',
                'color' => 'Brown',
                'taste_profile' => 'Creamy',
                'season' => 'All Year',
                'is_seasonal' => false,
                'price_per_kg' => 2.80,
                'origin_country' => 'Indonesia',
                'description' => 'Coconuts are tropical fruits known for their white flesh and hydrating water.',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Pomegranate',
                'scientific_name' => 'Punica granatum',
                'color' => 'Red',
                'taste_profile' => 'Tangy',
                'season' => 'Autumn',
                'is_seasonal' => true,
                'price_per_kg' => 4.30,
                'origin_country' => 'Iran',
                'description' => 'Pomegranates are nutrient-rich fruits with juicy, seed-filled arils and strong antioxidant properties.',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Papaya',
                'scientific_name' => 'Carica papaya',
                'color' => 'Orange',
                'taste_profile' => 'Sweet',
                'season' => 'All Year',
                'is_seasonal' => false,
                'price_per_kg' => 2.20,
                'origin_country' => 'Malaysia',
                'description' => 'Papayas are tropical fruits with a soft, sweet flesh that supports digestion and immune health.',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Guava',
                'scientific_name' => 'Psidium guajava',
                'color' => 'Green',
                'taste_profile' => 'Sweet',
                'season' => 'Autumn',
                'is_seasonal' => true,
                'price_per_kg' => 2.00,
                'origin_country' => 'Vietnam',
                'description' => 'Guavas are tropical fruits with fragrant flesh and a balance of sweet and tart flavors.',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Durian',
                'scientific_name' => 'Durio zibethinus',
                'color' => 'Green',
                'taste_profile' => 'Creamy',
                'season' => 'Summer',
                'is_seasonal' => true,
                'price_per_kg' => 7.00,
                'origin_country' => 'Malaysia',
                'description' => 'Durian is a spiky tropical fruit known for its strong odor and rich, custard-like taste.',
                'created_at' => now(),
                'updated_at' => now(),
            ],
        ];

        DB::table('fruits')->insert($fruits);
    }
}
