<?php

//  ---------------------------------------- DO NOT EDIT THIS FILE  ---------------------------------------- //
//  ---------------------------------------- DO NOT EDIT THIS FILE  ---------------------------------------- //
//  ---------------------------------------- DO NOT EDIT THIS FILE  ---------------------------------------- //
use Illuminate\Support\Facades\Route;



// Routes of the modules to be use
foreach(glob(base_path('routes/modules/v1/*.php')) as $file){
    include $file;
}
foreach(glob(base_path('routes/modules/v2/*.php')) as $file){
    include $file;
}
foreach(glob(base_path('routes/modules/*.php')) as $file){
    include $file;
}


//  ---------------------------------------- DO NOT EDIT THIS FILE  ---------------------------------------- //
//  ---------------------------------------- DO NOT EDIT THIS FILE  ---------------------------------------- //
//  ---------------------------------------- DO NOT EDIT THIS FILE  ---------------------------------------- //
